# Generated by Django 2.2 on 2020-10-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('artist', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('album_art', models.ImageField(upload_to='album_art')),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('BL', 'Blues'), ('CO', 'Country'), ('CL', 'Classical'), ('HH', 'Hip-Hop/Rap'), ('JZ', 'Jazz'), ('RK', 'Rock'), ('RB', 'R&B/Soul')], default='BL', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60)),
                ('last_name', models.CharField(default=None, max_length=60)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('phone_number', models.IntegerField(blank=True, default=None, null=True)),
                ('delivery_instructions', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residents', models.ManyToManyField(related_name='shipping_address', to='record_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60)),
                ('last_name', models.CharField(default=None, max_length=60)),
                ('card_number', models.CharField(max_length=19)),
                ('expiration', models.CharField(max_length=5)),
                ('security_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_card', to='record_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=1, max_length=2)),
                ('charged_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charged_by', to='record_app.Payment')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='record_app.Product')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='record_app.User')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_of', to='record_app.ShippingAddress')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_to', models.ManyToManyField(related_name='billing_address', to='record_app.User')),
            ],
        ),
    ]
