# Generated by Django 2.2 on 2020-10-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0002_auto_20201013_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contents',
        ),
        migrations.AddField(
            model_name='order',
            name='contents',
            field=models.ManyToManyField(related_name='shopping_cart', to='record_app.Product'),
        ),
    ]
