# Generated by Django 2.2 on 2020-10-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0003_auto_20201015_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charged_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charged_by', to='record_app.Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_of', to='record_app.ShippingAddress'),
        ),
    ]
