# Generated by Django 2.2 on 2020-10-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0005_order_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contents',
            field=models.ManyToManyField(related_name='orders', to='record_app.Product'),
        ),
    ]
