# Generated by Django 2.2 on 2020-10-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0008_auto_20201030_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('BL', 'Blues'), ('CO', 'Country'), ('CL', 'Classical'), ('HH', 'Hip-Hop/Rap'), ('JZ', 'Jazz'), ('RK', 'Rock'), ('RB', 'R&B/Soul')], default='BL', max_length=2),
        ),
    ]
