# Generated by Django 2.2 on 2020-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0011_auto_20201109_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
